'use client';
import {createContext,useCallback,useContext,useEffect,useMemo,useState} from 'react';
import {CartLine,Currency} from '@/lib/types';import {DEFAULT_SHIPPING_FEES} from '@/lib/shipping';import {supabaseBrowser} from '@/lib/supabase-browser';
type Store={currency:Currency;setCurrency:(c:Currency)=>void;shippingFees:Record<Currency,number>;cart:CartLine[];add:(line:CartLine)=>void;remove:(id:string,size:string)=>void;quantity:(id:string,size:string,n:number)=>void;clear:()=>void;count:number;toast:string;notify:(s:string)=>void;wishlist:string[];toggleWish:(id:string)=>void;dark:boolean;toggleTheme:()=>void};const C=createContext<Store|null>(null);
export function StoreProvider({children}:{children:React.ReactNode}){
 const[currency,setCurrency]=useState<Currency>('NGN'),[cart,setCart]=useState<CartLine[]>([]),[wishlist,setWishlist]=useState<string[]>([]),[toast,setToast]=useState(''),[dark,setDark]=useState(false),[shippingFees,setShippingFees]=useState(DEFAULT_SHIPPING_FEES),[hydrated,setHydrated]=useState(false),[connected,setConnected]=useState(false);
 useEffect(()=>{try{setCurrency((localStorage.getItem('currency') as Currency)||'NGN');setCart(JSON.parse(localStorage.getItem('cart')||'[]'));setWishlist(JSON.parse(localStorage.getItem('wishlist')||'[]'));const t=localStorage.getItem('theme');setDark(t==='dark'||(!t&&matchMedia('(prefers-color-scheme: dark)').matches))}catch{}setHydrated(true);fetch('/api/shipping').then(r=>r.ok?r.json():null).then(v=>{if(v&&Number.isFinite(v.NGN)&&Number.isFinite(v.USD))setShippingFees(v)}).catch(()=>{})},[]);
 useEffect(()=>{if(!hydrated)return;const sb=supabaseBrowser();if(!sb)return;let cancelled=false;sb.auth.getUser().then(async({data})=>{if(cancelled||!data.user)return;try{const[cr,wr]=await Promise.all([fetch('/api/customer/cart',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'merge',items:cart.filter(i=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(i.productId))})}),fetch('/api/customer/wishlist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'merge',items:wishlist.filter(i=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(i))})})]);if(cancelled)return;if(cr.ok){const d=await cr.json();setCart(d.items)}if(wr.ok){const d=await wr.json();setWishlist(d.items)}setConnected(true)}catch{}});return()=>{cancelled=true}},[hydrated]);
 useEffect(()=>{localStorage.setItem('cart',JSON.stringify(cart))},[cart]);useEffect(()=>{localStorage.setItem('wishlist',JSON.stringify(wishlist))},[wishlist]);
 useEffect(()=>{if(!connected)return;const timer=setTimeout(()=>{fetch('/api/customer/cart',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'replace',items:cart})})},300);return()=>clearTimeout(timer)},[connected,cart]);useEffect(()=>{if(!connected)return;const timer=setTimeout(()=>{fetch('/api/customer/wishlist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'replace',items:wishlist})})},300);return()=>clearTimeout(timer)},[connected,wishlist]);
 useEffect(()=>{localStorage.setItem('currency',currency)},[currency]);useEffect(()=>{localStorage.setItem('theme',dark?'dark':'light');document.documentElement.classList.toggle('dark',dark)},[dark]);
 const notify=useCallback((s:string)=>{setToast(s);setTimeout(()=>setToast(''),2400)},[]),add=useCallback((line:CartLine)=>setCart(x=>{const old=x.find(i=>i.productId===line.productId&&i.size===line.size);notify(old?'Quantity updated':'Added to your bag');return old?x.map(i=>i===old?{...i,quantity:i.quantity+line.quantity}:i):[...x,line]}),[notify]),remove=useCallback((id:string,size:string)=>setCart(x=>x.filter(i=>i.productId!==id||i.size!==size)),[]),quantity=useCallback((id:string,size:string,n:number)=>setCart(x=>x.map(i=>i.productId===id&&i.size===size?{...i,quantity:Math.max(1,n)}:i)),[]),clear=useCallback(()=>setCart([]),[]),toggleWish=useCallback((id:string)=>setWishlist(x=>{const on=x.includes(id);notify(on?'Removed from wishlist':'Saved to wishlist');return on?x.filter(v=>v!==id):[...x,id]}),[notify]),toggleTheme=useCallback(()=>setDark(x=>!x),[]);
 const value=useMemo(()=>({currency,setCurrency,shippingFees,cart,add,remove,quantity,clear,count:cart.reduce((a,b)=>a+b.quantity,0),toast,notify,wishlist,toggleWish,dark,toggleTheme}),[currency,shippingFees,cart,add,remove,quantity,clear,toast,notify,wishlist,toggleWish,dark,toggleTheme]);return <C.Provider value={value}>{children}{toast&&<div className="toast" role="status">{toast}</div>}</C.Provider>
}
export function useStore(){const v=useContext(C);if(!v)throw new Error('Store provider missing');return v}
