create extension if not exists pgcrypto;
create type public.user_role as enum ('customer','admin');
create type public.order_status as enum ('pending','paid','processing','shipped','delivered','cancelled');
create type public.payment_status as enum ('pending','paid','failed','refunded');
create table public.profiles(id uuid primary key references auth.users on delete cascade,email text not null,full_name text,phone text,avatar_url text,role public.user_role not null default 'customer',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.categories(id uuid primary key default gen_random_uuid(),name text not null unique,slug text not null unique,description text,image text,created_at timestamptz not null default now());
create table public.products(id uuid primary key default gen_random_uuid(),name text not null,slug text not null unique,brand text not null check(brand in('Nike','Adidas')),description text not null default '',category_id uuid references public.categories on delete set null,price_ngn bigint not null check(price_ngn>=0),price_usd numeric(12,2) not null check(price_usd>=0),compare_at_price_ngn bigint,compare_at_price_usd numeric(12,2),images text[] not null default '{}',featured boolean not null default false,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.product_sizes(id uuid primary key default gen_random_uuid(),product_id uuid not null references public.products on delete cascade,size text not null,stock_quantity integer not null default 0 check(stock_quantity>=0),unique(product_id,size));
create table public.carts(id uuid primary key default gen_random_uuid(),user_id uuid not null unique references public.profiles on delete cascade,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.cart_items(id uuid primary key default gen_random_uuid(),cart_id uuid not null references public.carts on delete cascade,product_id uuid not null references public.products,size text not null,quantity integer not null check(quantity>0),created_at timestamptz not null default now(),unique(cart_id,product_id,size));
create table public.wishlists(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles on delete cascade,product_id uuid not null references public.products on delete cascade,created_at timestamptz not null default now(),unique(user_id,product_id));
create table public.orders(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles,order_number text not null unique default ('FS-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,12))),status public.order_status not null default 'pending',payment_status public.payment_status not null default 'pending',payment_reference text unique not null,payment_access_code text,currency text not null check(currency in('NGN','USD')),subtotal numeric(14,2) not null,shipping_fee numeric(14,2) not null,total numeric(14,2) not null,total_minor bigint not null,customer_name text not null,customer_email text not null,customer_phone text not null,shipping_address text not null,shipping_city text not null,shipping_state text not null,shipping_country text not null,postal_code text,paid_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.order_items(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders on delete cascade,product_id uuid references public.products on delete set null,product_name_snapshot text not null,product_price_snapshot numeric(14,2) not null,currency text not null,size text not null,quantity integer not null check(quantity>0),subtotal numeric(14,2) not null);
create table public.payment_events(id uuid primary key default gen_random_uuid(),reference text not null,event_type text not null,payload jsonb not null,created_at timestamptz not null default now(),unique(reference,event_type));
create table public.email_outbox(id uuid primary key default gen_random_uuid(),order_id uuid not null unique references public.orders on delete cascade,sent_at timestamptz,attempts int not null default 0,last_error text);
create index products_active_brand_idx on public.products(active,brand);create index orders_user_created_idx on public.orders(user_id,created_at desc);create index order_items_order_idx on public.order_items(order_id);
create function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,email,full_name,avatar_url) values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name',new.raw_user_meta_data->>'name'),new.raw_user_meta_data->>'avatar_url');insert into public.carts(user_id) values(new.id);return new;end$$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create function public.create_reserved_order(p_user_id uuid,p_customer jsonb,p_currency text,p_items jsonb,p_shipping_fee numeric) returns jsonb language plpgsql security definer set search_path=public as $$
declare item jsonb; p public.products%rowtype; v_size public.product_sizes%rowtype; v_price numeric; v_subtotal numeric:=0; v_shipping numeric; v_order public.orders%rowtype; v_ref text:=replace(gen_random_uuid()::text,'-','');
begin
 if p_currency not in('NGN','USD') then raise exception 'currency'; end if;
 for item in select value from jsonb_array_elements(p_items) loop
   select * into p from public.products where id=(item->>'productId')::uuid and active for share;
   if not found then raise exception 'product inactive'; end if;
   select * into v_size from public.product_sizes where product_id=p.id and size=item->>'size' for update;
   if not found or v_size.stock_quantity < (item->>'quantity')::int then raise exception 'stock unavailable'; end if;
   v_price:=case when p_currency='NGN' then p.price_ngn else p.price_usd end; v_subtotal:=v_subtotal+v_price*(item->>'quantity')::int;
 end loop;
 if p_shipping_fee<0 then raise exception 'shipping fee'; end if; v_shipping:=p_shipping_fee;
 insert into public.orders(user_id,payment_reference,currency,subtotal,shipping_fee,total,total_minor,customer_name,customer_email,customer_phone,shipping_address,shipping_city,shipping_state,shipping_country,postal_code)
 values(p_user_id,v_ref,p_currency,v_subtotal,v_shipping,v_subtotal+v_shipping,round((v_subtotal+v_shipping)*case when p_currency='NGN' then 100 else 100 end),p_customer->>'name',p_customer->>'email',p_customer->>'phone',p_customer->>'address',p_customer->>'city',p_customer->>'state',p_customer->>'country',p_customer->>'postal_code') returning * into v_order;
 for item in select value from jsonb_array_elements(p_items) loop
   select * into p from public.products where id=(item->>'productId')::uuid;
   update public.product_sizes set stock_quantity=stock_quantity-(item->>'quantity')::int where product_id=p.id and size=item->>'size';
   v_price:=case when p_currency='NGN' then p.price_ngn else p.price_usd end;
   insert into public.order_items(order_id,product_id,product_name_snapshot,product_price_snapshot,currency,size,quantity,subtotal) values(v_order.id,p.id,p.name,v_price,p_currency,item->>'size',(item->>'quantity')::int,v_price*(item->>'quantity')::int);
 end loop;
 return jsonb_build_object('id',v_order.id,'order_number',v_order.order_number,'payment_reference',v_order.payment_reference,'total_minor',v_order.total_minor,'total',v_order.total);
end$$;
create function public.release_order_reservation(p_order_id uuid,p_status text) returns void language plpgsql security definer set search_path=public as $$begin if exists(select 1 from public.orders where id=p_order_id and payment_status='pending') then update public.product_sizes s set stock_quantity=s.stock_quantity+i.quantity from public.order_items i where i.order_id=p_order_id and s.product_id=i.product_id and s.size=i.size;update public.orders set payment_status='failed',status='cancelled',updated_at=now() where id=p_order_id;end if;end$$;
create function public.release_order_by_reference(p_reference text,p_status text) returns void language plpgsql security definer set search_path=public as $$declare oid uuid;begin select id into oid from public.orders where payment_reference=p_reference;if oid is not null then perform public.release_order_reservation(oid,p_status);end if;end$$;
create function public.confirm_paystack_order(p_reference text,p_amount_minor bigint,p_currency text) returns jsonb language plpgsql security definer set search_path=public as $$declare o public.orders%rowtype;begin select * into o from public.orders where payment_reference=p_reference for update;if not found then return jsonb_build_object('error','Order not found');end if;if o.payment_status='paid' then return jsonb_build_object('order_number',o.order_number);end if;if o.total_minor<>p_amount_minor or o.currency<>p_currency then return jsonb_build_object('error','Payment amount mismatch');end if;insert into public.payment_events(reference,event_type,payload) values(p_reference,'charge.success',jsonb_build_object('amount',p_amount_minor,'currency',p_currency)) on conflict do nothing;update public.orders set payment_status='paid',status='paid',paid_at=now(),updated_at=now() where id=o.id;insert into public.email_outbox(order_id) values(o.id) on conflict do nothing;return jsonb_build_object('order_number',o.order_number);end$$;
alter table public.profiles enable row level security;alter table public.categories enable row level security;alter table public.products enable row level security;alter table public.product_sizes enable row level security;alter table public.carts enable row level security;alter table public.cart_items enable row level security;alter table public.wishlists enable row level security;alter table public.orders enable row level security;alter table public.order_items enable row level security;alter table public.payment_events enable row level security;alter table public.email_outbox enable row level security;
create function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.profiles where id=auth.uid() and role='admin')$$;
create policy "Public sees active products" on public.products for select using(active or public.is_admin());create policy "Admin manages products" on public.products for all using(public.is_admin()) with check(public.is_admin());
create policy "Public sees categories" on public.categories for select using(true);create policy "Admin manages categories" on public.categories for all using(public.is_admin()) with check(public.is_admin());
create policy "Public sees active sizes" on public.product_sizes for select using(exists(select 1 from public.products p where p.id=product_id and p.active) or public.is_admin());create policy "Admin manages sizes" on public.product_sizes for all using(public.is_admin()) with check(public.is_admin());
create policy "Own profile read" on public.profiles for select using(id=auth.uid() or public.is_admin());create policy "Own profile update" on public.profiles for update using(id=auth.uid()) with check(id=auth.uid());create policy "Admin reads profiles" on public.profiles for all using(public.is_admin()) with check(public.is_admin());
create policy "Own carts" on public.carts for all using(user_id=auth.uid() or public.is_admin()) with check(user_id=auth.uid() or public.is_admin());create policy "Own cart items" on public.cart_items for all using(exists(select 1 from public.carts c where c.id=cart_id and c.user_id=auth.uid()) or public.is_admin()) with check(exists(select 1 from public.carts c where c.id=cart_id and c.user_id=auth.uid()) or public.is_admin());
create policy "Own wishlist" on public.wishlists for all using(user_id=auth.uid() or public.is_admin()) with check(user_id=auth.uid() or public.is_admin());create policy "Own orders" on public.orders for select using(user_id=auth.uid() or public.is_admin());create policy "Admin updates orders" on public.orders for update using(public.is_admin()) with check(public.is_admin());create policy "Own order items" on public.order_items for select using(exists(select 1 from public.orders o where o.id=order_id and (o.user_id=auth.uid() or public.is_admin())));
revoke all on function public.create_reserved_order(uuid,jsonb,text,jsonb,numeric) from public,anon,authenticated;revoke all on function public.release_order_reservation(uuid,text) from public,anon,authenticated;revoke all on function public.release_order_by_reference(text,text) from public,anon,authenticated;revoke all on function public.confirm_paystack_order(text,bigint,text) from public,anon,authenticated;grant execute on function public.create_reserved_order(uuid,jsonb,text,jsonb,numeric),public.release_order_reservation(uuid,text),public.release_order_by_reference(text,text),public.confirm_paystack_order(text,bigint,text) to service_role;

create function public.prevent_role_escalation() returns trigger language plpgsql security definer set search_path=public as $$begin if new.role<>old.role and auth.uid() is not null and not public.is_admin() then raise exception 'role changes require an administrator';end if;return new;end$$; create trigger profiles_role_guard before update on public.profiles for each row execute procedure public.prevent_role_escalation();

create table public.newsletter_subscribers(id uuid primary key default gen_random_uuid(),email text not null unique,subscribed_at timestamptz not null default now(),source text not null default 'website');alter table public.newsletter_subscribers enable row level security;
